<div dir = "rtl">

این نوت‌بوک قرار است کل فرآیند ورود داده و پاک‌سازی را به‌شکل مرحله‌به‌مرحله و قابل ارائه نشان دهد. مزیت نوت‌بوک این است که می‌توانید ببینید:

    - داده از کجا آمده،
    - چطور پاک‌سازی شده،
    - چه کنترل‌هایی روی کیفیت انجام شده،
    - و چگونه وارد پایگاه داده شده است.

In [1]:
import sys
from pathlib import Path
import sqlite3
import pandas as pd
project_root = Path.cwd().parent
if str(project_root)not in sys.path:
    sys.path.append(str(project_root))
from src.cleaning import combine_all_files, run_quality_checks, save_outputs

In [2]:
DATA_DIR = project_root / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
DB_PATH = project_root / "db" / "energy_load.db"

In [3]:
df = combine_all_files(RAW_DIR)
df.head()

,source_file,interval_start,interval_end,week_label,week_number,area_name,area_code,forecast_min_mw,actual_min_mw,actual_max_mw,forecast_max_mw,data_year,created_at
0,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31,2019-12-30,Week 1,1,Poland,PL,12898.5,12992.96,24945.56,27700.0,2019,2026-07-06 20:09:35
1,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31,2019-12-30,Week 2,2,Poland,PL,14170.9,15513.79,25954.28,27700.0,2019,2026-07-06 20:09:35
2,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31,2019-12-30,Week 3,3,Poland,PL,15434.4,15798.93,25264.46,27700.0,2019,2026-07-06 20:09:35
3,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31,2019-12-30,Week 4,4,Poland,PL,15483.2,16055.43,26135.58,27700.0,2019,2026-07-06 20:09:35
4,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31,2019-12-30,Week 5,5,Poland,PL,15090.6,14985.68,25339.89,27700.0,2019,2026-07-06 20:09:35

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   source_file      418 non-null    str
 1   interval_start   418 non-null    datetime64[us]
 2   interval_end     418 non-null    datetime64[us]
 3   week_label       418 non-null    str
 4   week_number      418 non-null    int64
 5   area_name        418 non-null    str
 6   area_code        418 non-null    str
 7   forecast_min_mw  418 non-null    float64
 8   actual_min_mw    392 non-null    float64
 9   actual_max_mw    392 non-null    float64
 10  forecast_max_mw  418 non-null    float64
 11  data_year        418 non-null    int32
 12  created_at       418 non-null    datetime64[us]
dtypes: datetime64[us](3), float64(4), int32(1), int64(1), str(4)
memory usage: 40.9 KB

In [5]:
df.isna().sum()

source_file         0
interval_start      0
interval_end        0
week_label          0
week_number         0
area_name           0
area_code           0
forecast_min_mw     0
actual_min_mw      26
actual_max_mw      26
forecast_max_mw     0
data_year           0
created_at          0
dtype: int64

In [6]:
quality_report = run_quality_checks(df)
quality_report

{'row_count': 418,
 'missing_values': {'source_file': 0,
  'interval_start': 0,
  'interval_end': 0,
  'week_label': 0,
  'week_number': 0,
  'area_name': 0,
  'area_code': 0,
  'forecast_min_mw': 0,
  'actual_min_mw': 26,
  'actual_max_mw': 26,
  'forecast_max_mw': 0,
  'data_year': 0,
  'created_at': 0},
 'duplicate_rows': 0,
 'duplicate_business_keys': 54,
 'invalid_week_numbers': 0,
 'invalid_date_ranges': 0,
 'invalid_min_max_actual': 0,
 'invalid_min_max_forecast': 0}

In [7]:
processed_csv_path, db_path = save_outputs(df)
processed_csv_path, db_path

(WindowsPath('d:/my computer/taha/zohram/Analyture/02_project/01_energy-load-project/data/processed/weekly_load_cleaned.csv'),
 WindowsPath('d:/my computer/taha/zohram/Analyture/02_project/01_energy-load-project/db/energy_load.db'))

In [8]:
conn = sqlite3.connect(DB_PATH)
query = "SELECT * FROM weekly_load LIMIT 10;"
preview_df = pd.read_sql_query(query, conn)
conn.close()
preview_df

,source_file,interval_start,interval_end,week_label,week_number,area_name,area_code,forecast_min_mw,actual_min_mw,actual_max_mw,forecast_max_mw,data_year,created_at
0,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31 00:00:00,2019-12-30 00:00:00,Week 1,1,Poland,PL,12898.5,12992.96,24945.56,27700.0,2019,2026-07-06 20:09:35
1,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31 00:00:00,2019-12-30 00:00:00,Week 2,2,Poland,PL,14170.9,15513.79,25954.28,27700.0,2019,2026-07-06 20:09:35
2,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31 00:00:00,2019-12-30 00:00:00,Week 3,3,Poland,PL,15434.4,15798.93,25264.46,27700.0,2019,2026-07-06 20:09:35
3,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31 00:00:00,2019-12-30 00:00:00,Week 4,4,Poland,PL,15483.2,16055.43,26135.58,27700.0,2019,2026-07-06 20:09:35
4,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31 00:00:00,2019-12-30 00:00:00,Week 5,5,Poland,PL,15090.6,14985.68,25339.89,27700.0,2019,2026-07-06 20:09:35
5,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31 00:00:00,2019-12-30 00:00:00,Week 6,6,Poland,PL,15084.5,15152.40,24931.56,27400.0,2019,2026-07-06 20:09:35
6,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31 00:00:00,2019-12-30 00:00:00,Week 7,7,Poland,PL,15570.6,14766.14,24699.60,27400.0,2019,2026-07-06 20:09:35
7,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31 00:00:00,2019-12-30 00:00:00,Week 8,8,Poland,PL,15452.3,15221.48,24560.56,27400.0,2019,2026-07-06 20:09:35
8,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31 00:00:00,2019-12-30 00:00:00,Week 9,9,Poland,PL,16332.0,15023.25,24220.56,27400.0,2019,2026-07-06 20:09:35
9,GUI_TOTAL_LOAD_YEARAHEAD_201812312300-20191231...,2018-12-31 00:00:00,2019-12-30 00:00:00,Week 10,10,Poland,PL,16145.4,14460.68,23769.44,26100.0,2019,2026-07-06 20:09:35